[repo]
git_dir = "/home/andriishafar/.local/share/hometree/repo.git"
work_tree = "/home/andriishafar"

[manage]
paths = [
    ".bashrc",
    ".bash_profile",
    ".bash-preexec.sh",
    ".gitconfig",
    ".config/hometree/config.toml",
    ".profile",
    "src/charidy/bootstrap.sh",
    ".var/app/com.github.wwmm.easyeffects/config/easyeffects/db",
    ".var/app/com.github.wwmm.easyeffects/data/easyeffects/output",
    ".local/bin/get-ghostty-themes.sh",
    ".local/bin/mkv_to_h265_mp4.sh",
    ".local/bin/noctalia-gnome-theme-sync.sh",
    ".local/bin/toggle-mic.sh",
]

[ignore]
patterns = [
    "environment.sh",
    ".ssh/config",
    ".ssh/github.pub",
]

[watch]
enabled = false
debounce_ms = 500
auto_stage_tracked_only = true
auto_add_new = false
auto_add_allow_patterns = []

[snapshot]

[secrets]
enabled = true
backend = "age"
sidecar_suffix = ".age"
recipients = ["age1fud0m6700d43m8ne35qsunk07umfepzxd9hw59kh0uyu7u6jr5csgfw4c7"]
identity_files = ["/home/andriishafar/identity.txt"]
backup_policy = "encrypt"

[[secrets.rules]]
path = "environment.sh"

[[secrets.rules]]
path = ".ssh/config"

[[secrets.rules]]
path = ".ssh/github.pub"
