[tools]
bun = "latest"
cargo = "latest"
cargo-binstall = "latest"
"cargo:broot" = "latest"
"cargo:fresh-editor" = "latest"
"cargo:sd" = "latest"
go = "latest"
"go:github.com/cweill/gotests/gotests" = "latest"
"go:github.com/fatih/gomodifytags" = "latest"
"go:github.com/go-delve/delve/cmd/dlv" = "latest"
"go:github.com/haya14busa/goplay/cmd/goplay" = "latest"
"go:github.com/jesseduffield/lazydocker" = "latest"
"go:github.com/josharian/impl" = "latest"
"go:golang.org/x/tools/gopls" = "latest"
"go:honnef.co/go/tools/cmd/staticcheck" = "latest"
node = "24"
npm = "latest"
"npm:@google/gemini-cli" = "latest"
"npm:@just-every/code" = "latest"
"npm:@openai/codex" = "latest"
"npm:wrangler" = "latest"
pnpm = "latest"
rust = "stable"
usage = "latest"
zig = "latest"

[settings]
experimental = false
